version: 2.1

jobs:
  "test":
    parameters:
      version:
        type: string
        default: "1.18"
      latest:
        type: boolean
        default: false
      image:
        type: string
        default: "cimg/go"
      working_directory:
        type: string
        default: "/home/circleci/go/src/github.com/tyler-sommer/stick"
    docker:
      - image: "<< parameters.image >>:<< parameters.version >>"
    working_directory: "<< parameters.working_directory >>"
    environment:
      GO111MODULE: "on"
    steps:
      - when:
          condition:
            equal: [ true, << parameters.latest >> ]
          steps:
            - run:
                name: "Install latest version of Go"
                command: |
                  GO_LATEST=$(curl https://go.dev/dl/?mode=json | jq -r '.[0].version')
                  go install golang.org/dl/$GO_LATEST@latest
                  $GO_LATEST download
                  alias go=$GO_LATEST
      - checkout
      - run:
          name: "Print Go version"
          command: go version
      - run:
          name: "Install dependencies"
          command: go get -v ./...
      - when:
          condition:
            equal: [ true, << parameters.latest >> ]
          steps:
            - run:
                name: "Run go vet"
                command: go vet -v ./...
            - run:
                name: "Run goimports"
                command: |
                  go install golang.org/x/tools/cmd/goimports@latest
                  diff -u <(echo -n) <(goimports -d -e .)
      - run:
          name: "Run go test"
          command: go test -v -race ./...

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              version: [ "1.18", "1.17", "1.16", "1.15", "1.14", "1.13", "1.12", "1.11", "1.10" ]
      - test:
          matrix:
            parameters:
              working_directory: [ "/go/src/github.com/tyler-sommer/stick" ]
              image: [ "circleci/go" ]
              version: [ "1.9", "1.8", "1.7" ]
      - test:
          matrix:
            parameters:
              latest: [ true ]
